hmcts/sds-azure-platform

azure-pipelines-frontdoor.yaml
azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-242
Moving frontdoor deployment to separate pipeline until the sorting is fixed. 
Pipeline name is current "SDS Azure Platform - frontdoor" let me know if it should be something different. 
```
[ ] Yes
[x] No
```

DTSPO-242 - separate frontdoor and app gw pipelines

---

environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/sbox/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

Exclude the environment name in the app name, so that the domains will appear as e.g. 
'toffee-recipe-backend.staging.platform.hmcts.net' instead of 'toffee-recipe-backend-stg.staging.platform.hmcts.net'
```
[ ] Yes
[x] No
```

DTSPO-658 Exclude Env Name in App Name

---

environments/prod/prod.tfvars

jd-bureau and reply-summons are both apex domains so managed certificates cannot be used﻿

DTSPO-4364 - Reverting FrontDoor to KeyVault

---

components/apim/local.tf
components/apim/main.tf
environments/variable.tf

add default next hop IP to Palo for APIM
- Did not add the other .tfvars in terms of the "hub" as not sure which environments we will deploy APIM onto yet
```
[ ] Yes
[X] No
```

add default next hop IP to Palo for APIM

---

components/apim/init.tf

Bumping apim terraform to 2.97.0
- Will manually delete sbox apim before merging as its deployed using terraform arm template
```
[ ] Yes
[X] No
```

Bumping apim terraform to 2.97.0

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-1117
Az Fd is currently blocking the tokens returned by Azure Open ID due to the characters in the body.
This exclusion should allow these parameters to bypass
```
[ ] Yes
[ x ] No
```

PUB-1117 - exclude open id body parameters

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

N/A
Added exclusion to cookiePolicy for pip-frontend. This cookie is used to store preferences for the user, and is currently being blocked.
```
[ ] Yes
[x] No
```

Added cookie exclusion for PIP Frontend

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

N/A
Added a further cookie to PIP Frontend. This cookie is used in the create-admin-account screens to store state. It's currently being blocked by frontdoor.
```
[ ] Yes
[x] No
```

PIP-Frontend - Further Cookie

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DSTP0-9055
Remove custom rule that restricts toffee sbox to connections on vpn
Terraform plan will attempt to destroy some vh-admin and video web related resources (not related to this pr) but these are failing in the latest applies anyway.
```
[ ] Yes
[x] No
```

DTSPO-9055 - Remove toffee sbox custom rules

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-12424 
This code:
- Adds both demo clusters as backend targets for backends in this appgw
- Includes toffee in the appgw backend pool
- Depends on PIP creation in https://github.com/hmcts/rdo-terraform-hub-dmz/pull/723/files
```
[ ] Yes
[ ] No
```

Included toffee as a frontend, added both clusters as destinations

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/RST-5234
Azure FrontDoor is suddenly blocking requests on the /Admin urls.
See if this custom rule allows them
/Admin URL password protected an blocked by an MoJ VPN ip filter
```
[ ] Yes
[x] No
```

Azure FrontDoor is suddenly blocking requests on the /Admin urls.

---

environments/demo/backend_lb_config.yaml

This change:
- Fixes demo appgw not listening on port 443 for VH backends and causing app to not run
```
[ ] Yes
[ ] No
```

Add ssl_enabled flag to allow 443 listeners

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/PUB-2085
Remove old PIP DNS from frontend, as it is no longer used / does not work

PUB-2085 - Removed old pip frontend domain

---

components/frontdoor/main.tf

Send access logs to storage account to save a lot of money instead of log analytics

Send access logs to storage account

---

azure-pipelines.yaml
environments/dev/dev.tfvars

In order to solve this error on the frontdoor
```
The host 'dev.landregistrationdivision.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.immigrationservices.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.administrativeappeals.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.employmentappeals.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.financeandtax.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.landschamber.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.cicap.dsd.io' is missing a default route '/*' path for the HTTPS protocol.
The host 'dev.carestandards.dsd.io' is missing a …
```

fixing dev frontdoor

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-15318
Reverted CFT change in https://github.com/hmcts/azure-platform-terraform/pull/1835
Adds sbox-jenkins redirect to front door
CNAME added in https://github.com/hmcts/azure-public-dns/pull/1403

DTSPO-15318: Add sbox-jenkins redirect

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-15318
Adds redirect for sds sbox jenkins static  -- will add the cname records after , when I added before previously there was an error of 
```
Another custom domain with the same host name already exists.
```

DTSPO-15318: Add sds sbox jenkins static redirect

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-15318
After https://github.com/hmcts/sds-flux-config/pull/3709 this change adds a redirect to front door for sds jenkins

DTSPO-15318: Add front door redirect to sds jenkins

---

components/frontdoor/main.tf
environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars
environments/variable.tf

We do not need this upgrade_frontdoor field any more as all the frontdoors are now migrated to premium, we have to change the brach to master as well after merging the DTSPO-13992-test-new-version-of-frontdoor to master on the module.

post SDS frontdoor migration clean up

---

environments/demo/demo.tfvars
environments/stg/stg.tfvars

Test hosted_externally in stg
- Added a fix to resolve demo pipeline as well
Fixes error in pipeline for stg_frontdoor, that DNS zones we don't own
`##[error]Terraform command 'plan' failed with exit code '1'.
##[error]╷
│ Error: Dns Zone (Subscription: "ed302caf-ec27-4c64-a05e-85731c3ce90e"
│ Resource Group Name: "reformmgmtrg"
│ Dns Zone Name: "carestandards.dsd.io") was not found`

Test hosted_externally in stg and demo fix

---

environments/prod/prod.tfvars

Fix: 
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=482544&view=logs&j=c9c80ccb-7a58-5196-19c3-f88f021e4da5&t=1ac4a124-84c4-5f6e-41c3-e32a7eda5a2a 
Marking dns zones which are externally hosted.

FIX: marked dns zones which are externally hosted

---

azure-pipelines.yaml
scripts/apim.test.ts

- Updated APIM Prod stage to depend_on APIM Stg/AAT
- Updated [apim.test.ts](https://github.com/hmcts/azure-platform-terraform/pull/1910/files#diff-852523a669ece4bcd3cf4cccf2220690596c9387853a7882a78524f7bd971c0e)to a valid test
Testing:
- Did remove condition to allow tests to run on non `main` branch
[Successful test](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=491738&view=results)
[Failed test](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=491731&view=results)

add apim test and depend prod on stg apim

---

environments/demo/apim_appgw_config.yaml
environments/dev/apim_appgw_config.yaml
environments/ithc/apim_appgw_config.yaml
environments/prod/apim_appgw_config.yaml
environments/sbox/apim_appgw_config.yaml
environments/stg/apim_appgw_config.yaml
environments/test/apim_appgw_config.yaml

N/A
Added listener_host_name_suffix and listener_ssl_host_name_suffix properties to application gateway configuration files.  These are needed due to changes to terraform-module-apim-application-gateway (see https://github.com/hmcts/terraform-module-apim-application-gateway/pull/20).
- [no] Does this PR introduce a breaking change

Updated application gateway config

---

environments/demo/apim_appgw_config.yaml
environments/dev/apim_appgw_config.yaml
environments/ithc/apim_appgw_config.yaml
environments/prod/apim_appgw_config.yaml
environments/sbox/apim_appgw_config.yaml
environments/stg/apim_appgw_config.yaml
environments/test/apim_appgw_config.yaml

N/A
Removed listener_host_name_suffix and listener_ssl_host_name_suffix properties from application gateway configuration files.  These are no longer needed due to changes to terraform-module-apim-application-gateway (see https://github.com/hmcts/terraform-module-apim-application-gateway/pull/21).
- [no] Does this PR introduce a breaking change

Removed listener suffix properties from app gateway config

---

environments/prod/prod.tfvars

Disabled Cache to fix the issue with following sites
```
landregistrationdivision.decisions.tribunals.gov.uk
immigrationservices.decisions.tribunals.gov.uk
informationrights.decisions.tribunals.gov.uk
administrativeappeals.decisions.tribunals.gov.uk
carestandards.decisions.tribunals.gov.uk
landschamber.decisions.tribunals.gov.uk
financeandtax.decisions.tribunals.gov.uk
employmentappeals.decisions.tribunals.gov.uk
transportappeals.decisions.tribunals.gov.uk
cicap.decisions.tribunals.gov.uk
```

DTSPO-17265 - Disabling Cache

---

components/backendappgateway/main.tf
environments/prod/backend_lb_config.yaml

N/A
Sometimes when a large amount of processing is requested by the On-Prem GoB Application in Azure the application can take >60 seconds to respond.

feat: specify timeout for LibraGoB

---

azure-pipelines.yaml

added pipeline time limit variable added to precheck, steps and pipeline tests
- Modified azure-pipelines.yaml
- Added a timeoutInMinutes variable with a value of 90
- Updated the Validate, TerraformPlanApply, and PipelineTests jobs to include a timeoutInMinutes parameter referencing the newly added variable

add pipeline timeout for apim upgrade

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17760
migrate sds apim demo back to original resources
remove ithc vars no longer needed
- `environments/demo/demo.tfvars`:
- Changed `trigger_migration` from `true` to `false`.
- Updated `trigger_migration_temp_pip` to `true`.
- Updated `temp_subnet_address_prefixes` to `\"10.51.99.0/24\"`.
- `environments/ithc/ithc.tfvars`:
- Removed `migration_variables` block.
- Updated `min_protocol_version` to `\"TLSv1_2\"`.

migrate sds apim demo back to original resources

---

environments/dev/dev.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17814
Fixes DNS entry for vh-video-web-pr-2142.dev.platform.hmcts
- Modified `dev.tfvars`:
- Removed `vh-video-web-pr-2142` with custom domain `vh-video-web-pr-2142.dev.platform.hmcts.net`.
- Added `vh-video-web-pr-2142` with custom domain `vh-video-web-pr-2142.dev.platform.hmcts.net`, backend domain, disabled rules, cache enabled, and global exclusions.

Fix vh-video-web-pr-2142.dev.platform.hmcts record

---

environments/demo/demo.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17762
trigger migration of sds apim test to original resources
- Removed the `migration_variables` block with the fields `trigger_migration`, `trigger_migration_temp_pip`, and `temp_subnet_address_prefixes`.
- Updated the value of `hub_app_gw_private_ip_address` to `[\"10.11.72.230\"]`.
- Updated the value of `apim_appgw_backend_pool_fqdns` to `[\"firewall-nonprodi-palo-sdsapimgmtdemo.uksouth.cloudapp.azure.com\"]`.
- Updated the value of `key_vault_subscription` to `\"c68a4bed-4c3d-4956-af51-4ae164c1957c\"`.
- Changed the value of `trigger_migration` from `true` to `false`.
- Changed the value of `trigger_migration_temp_pip` to `true`.
- Updated the value of `temp_subnet_address_prefixes` to `\"10.141.35.0/24\"`.

DTSPO-17762-sds-apim-test-upgrade-pt2

---

azure-pipelines.yaml

updated pipeline timeout from 90 -> 60 minutes
- **azure-pipelines.yaml**
- Updated the `timeoutInMinutes` variable value from 90 to 60.

revert pipeline timeout back to 60 minutes

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/PUB-2503
Updated exclusion for false positive for CaTH
- Added a new match_variable, operator, and selector for the frontends in the stg.tfvars file.csrf_token has been added as a query string argument name.

PUB-2503 - Updated exclusion for false positive CaTH

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-18453
- Set min/max instances for stg apim appgw to 1/2
- Free's IP in subnet to allow aat apim appgw deployment
- Added `apim_appgw_min_capacity` and `apim_appgw_max_capacity` with values 1 and 2.

DTSPO-18453: min/max set to 1/2 for stg apim_appgw

---

components/apim/main.tf
environments/stg/stg.tfvars
environments/variable.tf

Allows for some snat ip ranges between ss-dev and ss-stg and uses new module changes to add these routes https://github.com/hmcts/cnp-module-api-mgmt-private/pull/55
- Added a new input variable \"additional_routes_apim\" and assigned the value from the input variable `var.additional_routes_apim`.
- Added additional routes configurations to the \"additional_routes_apim\" variable.
- Added a new input variable \"additional_routes_apim\" of type list(object) to define additional routes configurations.

Add additional routes to apim route table

---

environments/test/test.tfvars

- Removed the `disabled_rules` block and added `custom_rules` block.
- Changed the `health_protocol` and `forwarding_protocol` values.

pre-portal FW rules

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-2364
Add exclusion rule for pip-frontend non-prod QueryStringArgNames to avoid requests getting block after SSO sign-in
Have checked the firewall logs and saw that the requests are getting blocked because of the query param value contains too many special characters. It is a genuine false positive.
- Added new configuration for frontends with `match_variable`, `operator`, and `selector` for \"code\".
- Added new configuration for frontends with `match_variable`, `operator`, and `selector` for \"code\".
- Added new configuration for frontends with `match_variable`, `operator`, and `selector` for \"code\".
- Added new configuration for frontends with `match_variable`, `operator`, and `selector` for \"code\".

PUB-2364 Add exclusion rule for pip-frontend QueryStringArgNames

---

environments/test/test.tfvars

- The file `environments/test/test.tfvars` has been modified to add global exclusions for a match_variable \"QueryStringArgNames\" with operator \"Equals\" and selector \"code\" within custom rules. The RCE values have been removed and \"health_protocol\" has been set to \"Https\", \"forwarding_protocol\" to \"HttpsOnly\", and \"cache_enabled\" to \"false\".

Update PRE test env rules to match prod

---

environments/ithc/ithc.tfvars

Disable WAF rules in ITHC
Tested in ITHC env and false positive blocking has reduced in version 2.1
- `environments/ithc/ithc.tfvars`
- Added new disabled rules for General category with IDs 200002 and 200003.
- Removed several match_variable rules related to RequestCookieNames and RequestBodyPostArgNames.
- Updated the configuration for frontends and global_exclusions.

PUB-2727 Disable WAF rules in ITHC

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars

Update WAF ruleset to 2.1 in demo env
Tested in ITHC env and false positive blocking has reduced in version 2.1
- `environments/demo/demo.tfvars`:
- Added `ruleset_type` and `ruleset_value` properties.
- Updated `disabled_rules_action` and `disabled_rules` properties.
- `environments/stg/stg.tfvars`:
- Added `ruleset_type` and `ruleset_value` properties.
- Updated `disabled_rules_action` and `disabled_rules` properties.

PUB-2727 Update WAF ruleset to 2.1 for demo and staging env

---

environments/sbox/sbox.tfvars

Reverts hmcts/sds-azure-platform#889
- Removed the `additional_shutter_apps` block containing a `test-shutter-app-new` configuration.

Revert "adding test static app"

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-24370
We've had a request for the Front Door domains related to all *.decisions.tribunals.gov.uk to be removed. They are no longer required as the domains are hosted in AWS Cloud Platform Route53 as below.
This PR will be to remove the below
- carestandards.decisions.tribunals.gov.uk
- cicap.decisions.tribunals.gov.uk
Removed domain administrativeappeals.decisions.tribunals.gov.uk prior to this.
md
- prod.tfvars
- Removed configuration for \"trib-care-standards\" and \"trib-cicap\" services, including their specific configurations and rules for prevention mode
```

 remove domains care standards & cicap

---

components/apim/init.tf
components/appgateway/init.tf
components/backendappgateway/init.tf
components/shutter_static_webapp/init.tf
components/trafficmanager/init.tf

https://tools.hmcts.net/jira/browse/DTSPO-24542
Looks like backendapp-gateway and app-gateway components are now running TF v1.11.0
Bump the required_version to match this and fix the current failures
I checked the change log and 1.11.0 doesn't have any breaking changes
- **components/apim/init.tf**
- Updated the required Terraform version from \"1.10.4\" to \"1.11.0\".
- **components/appgateway/init.tf**
- Updated the required Terraform version from \"1.10.4\" to \"1.11.0\".
- **components/backendappgateway/init.tf**
- Updated the required Terraform version from \"1.10.4\" to \"1.11.0\".
- **components/shutter_static_webapp/init.tf**
- Updated the required Terraform version from \"1.10.4\" to \"1.11.0\".
- **components/trafficmanager/init.tf**
- Updated the required Terraform version …

Bump 1.10.4 to 1.11.0 on backendapp-gateway and app-gateway component

---

components/apim/init.tf
components/apim_appgw/init.tf
components/appgateway/init.tf
components/backendappgateway/init.tf
components/frontdoor/init.tf
components/shutter_static_webapp/init.tf
components/trafficmanager/init.tf
environments/stg/backend_lb_config.yaml

See [DTSPO-24171](https://tools.hmcts.net/jira/browse/DTSPO-24171)
The database can be slow to return replies and testing has shown 45 seconds is enough to prevent time out errors by the App Gateway.
Have tested the setting by manually changing the value in the Azure portal.  No testing required for this code, as it only requires the request_timeout: 45 value setting in the configuration file.
- components/apim/init.tf
- Upgraded the required Terraform version from 1.11.0 to 1.11.1.
- components/apim_appgw/init.tf
- Upgraded the required Terraform version from \">= 1.4.6\" to \">= 1.11.1\".
- components/appgateway/init.tf
- Upgraded the required Terraform version from 1.11.0 to 1.11.1.
- components/backendappgateway/init.tf
- Upgraded the required Terraform version from 1.11.0 to 1.11.1. …

Add-custom-timeout-darts-gw

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-24370https://tools.hmcts.net/jira/browse/DTSPO-24370
This PR is to remove "waf.tribunalsdecisions.service.gov.uk" and Mark Butler advised they previously used AFD and the WAF to act as a frontend for the tribunals decisions and utiac services hosted in AWS, but they have migrated all of these services to a new AWS platform and no longer require the Azure resources
Removed other domains on this merged PR - https://github.com/hmcts/sds-azure-platform/pull/901 
diff
environments/prod/prod.tfvars
- Removed a block for \"dts-legacy-apps---utiac\" from the frontends list, including its name, mode, custom_domain, dns_zone_name, backend_domain, and shutter_app attributes, as they are no longer necessary.
- Adjusted the custom_domain for \"jd-bureau\" to …

remove prod domain waf tribunals decisions 

---

environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/PUB-2778
Update WAF to ruleset 2.1 PIP B2C on demo env
- `environments/demo/demo.tfvars`
- Updated `ruleset_type` and `ruleset_value` to \"Microsoft_DefaultRuleSet\" and \"2.1\" respectively.
- Removed and reorganized several global exclusions for better clarity.
- Made adjustments to `match_variable`, `operator`, and `selector` attributes within global exclusions.

PUB-2778 Update WAF to ruleset 2.1 for PIP B2C on demo env

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars

Adding Courtfines FD config to Demo and ITHC
- `demo.tfvars`:
- Added a new configuration for \"hmcts-courtfines-demo\" with custom domain, DNS zone name, backend domain, and disabled rules.
- `ithc.tfvars`:
- Added a new configuration for \"hmcts-courtfines-ithc\" with custom domain, DNS zone name, backend domain, and disabled rules.

Adding Courtfines FD config to Demo and ITHC

---

environments/stg/stg.tfvars

Updated Courtfines CNAME
- Changed the `custom_domain` from \"courtfines-app-staging.staging.platform.hmcts.net\" to \"courtfines-app.staging.platform.hmcts.net\" for the \"hmcts-courtfines-staging\" frontend.

Updated Courtfines CNAME

---

components/backendappgateway/main.tf
environments/test/test.tfvars
environments/variable.tf

Reverts hmcts/sds-azure-platform#954
Reverting as enabling this was only temporary DTSPO-26574
ℹ️ main.tf
- Removed the `send_access_logs_to_log_analytics` variable from the `module \"backendappgateway\"` block.
⚙️ test.tfvars
- Updated the value of `ssl_certificate` from \"wildcard-test-platform-hmcts-net\" to \"wildcard-test-platform-hmcts-net\".
- Changed `send_access_logs_to_log_analytics` from true to removed.
📦 variable.tf
- Removed the `send_access_logs_to_log_analytics` variable definition.

Revert "temp enable app insights on sds test for dets-arm perf testing"

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars
environments/dev/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars
environments/stg/backend_lb_config.yaml
environments/stg/stg.tfvars

Added initial config for Appreg - FD and LB
- `environments/demo/backend_lb_config.yaml`:
- Added SSL configuration for a new product \"appreg\" and component \"api\".
- `environments/demo/demo.tfvars`:
- Added a new frontend configuration for \"AppReg\" with custom domain and backend domain.
- `environments/dev/backend_lb_config.yaml`:
- Added SSL configuration for a new product \"appreg\" and component \"api\".
- `environments/ithc/backend_lb_config.yaml`:
- Added SSL configuration for a new product \"appreg\" and component \"api\".
- `environments/ithc/ithc.tfvars`:
- Added a new frontend configuration for \"AppReg\" with custom domain and backend domain.
- `environments/stg/backend_lb_config.yaml`:
- Added SSL configuration for a new product \"appreg\" and component \"api\".
- …

ARCPOC-168 - Added AppReg FD initial config
