azure-pipelines.yaml
components/appgateway/init.tf
pipeline-templates/terraform.yaml

Added common variable file path 
https://tools.hmcts.net/jira/browse/DTSPO-242
```
[ ] Yes
[ x] No
```

dtspo242: added variable file

---

environments/variable.tf
pipeline-scripts/file-check-changes.sh
pipeline-templates/terraform.yaml

https://tools.hmcts.net/jira/browse/DTSPO-242
[ ] Yes
[ x] No
```

dtspo242: updated template and script

---

pipeline-templates/terraform.yaml

https://tools.hmcts.net/jira/browse/DTSPO-242
[ ] Yes
[ x] No
```

dtspo242: modified tfplan path

---

environments/variable.tf

dtspo242: modified the file in order to start TF apply

---

environments/dev/dev.tfvars

adding vh-user-api wildcard cert for dev ss-cluster

---

environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

Fixing backend domains for ithc, dev, stg and test frontdoors
```
[ ] Yes
[x] No
```

Dtspo 242 fix backend domains

---

azure-pipelines.yaml

Fixing dependency bug
```
[ ] Yes
[ x] No
```

Added "dependsOn" for the stage in azure pipeline

---

environments/prod/prod.tfvars

INC5156454
Forcing pipeline to run and apply terraform
```
[ ] Yes
[x] No
```

INC5156454 - force pipeline to run

---

azure-pipelines-frontdoor.yaml

Fixing timeout for front door pipeline
```
[ ] Yes
[x] No
```

Set timeoutInMinutes when applying terraform

---

environments/prod/prod.tfvars

Adding Search >> to global exclusions for financeandtax

---

environments/dev/backend_lb_config.yaml

adding vh dev environment

---

environments/dev/backend_lb_config.yaml

Ammended to point at the correct cert: *.dev.platform.hmcts.net
```
[ ] Yes
[x] No
```

DTSPO-658 Ammend certicicate name in dev/backend_lb_config.yaml

---

environments/dev/backend_lb_config.yaml

adding initial user-api healtcheck override test

---

components/backendappgateway/main.tf

DTSPO-658 Ammend backendappgateway source to master

---

environments/dev/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/sbox/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

adding all lower environments and removing user-api override

---

environments/prod/prod.tfvars

Adding new global exclusion initialbodycontents

---

environments/prod/prod.tfvars

update global exclusion - care standards tribunals

---

environments/prod/prod.tfvars

Disabling a rule triggering a false positive for user upload

---

environments/dev/backend_lb_config.yaml

Ammend dev/backend_lb_config.yaml

---

environments/dev/backend_lb_config.yaml
pipeline-templates/terraform.yaml

JIRA link ###
Ammend yaml file to enable changes applied to backend_lb_config.yaml to trigger apply
```
[ ] Yes
[x] No
```

DTSPO-658 Fix Dev

---

environments/dev/backend_lb_config.yaml

DTSPO-658 Appliation gateway

---

environments/dev/backend_lb_config.yaml

DTSPO-658 Appliation backend gateway

---

environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/sbox/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

DTSPO-658 Toffee:: Updated config

---

environments/prod/prod.tfvars

add global exclusion to carestandardstribunals config

---

environments/prod/prod.tfvars

Removing Toffee entries from PROD env

 Removing Toffee entries from PROD env

---

environments/prod/prod.tfvars

Snow: INC5203318
```
[ ] Yes
[x] No
```

INC5203318 Add exclusion

---

environments/dev/dev.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-3577
- Add jd-dev and jd-public to dev.tfvars
- Add IP whitelisting at frontdoor for: 81.134.202.29/32, 51.145.6.230/32,
194.33.192.0/25, 194.33.196.0/25, 195.59.75.0/24, 158.234.251.0/24, 158.234.250.0/24,
213.121.161.124/32, 51.145.4.100/32
```
[ ] Yes
[x] No
```

DTSPO-3577 Add jd-dev and jd-public to dev.tfvars

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-2848
```
[ ] Yes
[ ] No
```

DTSPO-2848 SDS stg re-ip

---

environments/dev/dev.tfvars

Set JD custom domains to:
- jdbureau.dev.platform.hmcts.net
- jdfrontend.dev.platform.hmcts.net
```
[ ] Yes
[x] No
```

DTSPO-4362 - fix jd dev

---

environments/dev/dev.tfvars

Fix the health probe path for JD apps
```
[ ] Yes
[x] No
```

DTSPO-4362 - fix health probe path for jd bureau and frontend

---

environments/dev/dev.tfvars
environments/prod/prod.tfvars

- Added frontdoor config for JD bureau and public
- tf fmt
```
[ ] Yes
[x] No
```

DTSPO-4363 - add front door config for jd bureau and public

---

azure-pipelines.yaml
components/shutter/local.tf
components/shutter/module_shutter.tf
environments/dev/dev.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
modules/shutter_page/cdn_endpoints.tf
modules/shutter_page/custom_domains.tf
modules/shutter_page/enable_https.tf
modules/shutter_page/templates/managedCustomHttps.json
modules/shutter_page/variable.tf

- Add shuttering for production to the pipeline
- Run Terraform fmt
- Migrate custom domain from arm deployment to tf resource.
- Add ability to not deploy shuttering infra if it's not needed
```
[ ] Yes
[x] No
```

DTSPO-4365 - add shuttering for prod

---

environments/stg/stg.tfvars

Re-add pip frontend stg config
```
[ ] Yes
[ X ] No
```

Pub 657 Re-add pip frontend stg config

---

environments/stg/stg.tfvars

Add HMI Case HQ
```
[ ] Yes
[ X ] No
```

Add HMI Case HQ

---

environments/stg/stg.tfvars

add business rules
```
[ ] Yes
[ X ] No
```

PUB-751 add business rules

---

components/backendappgateway/dns.tf

it's created in azure-private-dns

DTSPO-5038 Don't create DNS zone

---

environments/stg/backend_lb_config.yaml
environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/PUB-760
Add PIP services to stg frontdoor
```
[ ] Yes
[ X ] No
```

PUB-760 add pip services to stg backend

---

environments/sbox/sbox.tfvars

add frontdoor config for sds-api-mgmt sbox
```
[ ] Yes
[X] No
```

add frontdoor config for sds-api-mgmt sbox

---

environments/prod/prod.tfvars

Add WAF in detection mode to capture required exclusions for 6 x sites, using the original A record addresses from the DNS servers in the dsd AWS account
```
[ ] Yes
[x] No
```

add front door in prevent mode for public facing# sites

---

environments/prod/prod.tfvars

original PR that was merged to master has broken the pipeline, due to DNS being required to already be set up to point to front door.
broken commit: https://github.com/hmcts/sharedservices-azure-platform/commit/6bc611711232e1c29ff6da31df49e8cfc300e1d7
have create this PR to resolve the broken build by creating new waf.domain addresses and will redirect to those after this change goes through.
```
[ ] Yes
[x] No 
```

use waf subdomains pointed to sdshmcts-prod.azurefd.net on dns server

---

environments/prod/backend_lb_config.yaml
environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/PUB-1007
Add PIP backend apps to production
Setup PIP on production Frontdoor
```
[ ] Yes
[ x ] No
```

PUB-1007 - Add PIP backend apps and frontdoor config

---

environments/sbox/sbox.tfvars

housekeeping values file in sbox env

---

environments/prod/prod.tfvars

Remove the "--" from the unique "name" value of each frontend
This is because the custom_domain value has been modified, so we must delete the old entries and recreate new ones
```
[ ] Yes
[x] No
```

Remove the "--" from the unique "name" value of each frontend

---

environments/ithc/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/PUB-1042
Add the PIP applications to Test and ITHC config. All to be private on the backend apps
```
[ ] Yes
[ X ] No
```

PUB-1042 Add PIP App Confg

---

environments/demo/demo.tfvars

DTSPO-6478 - Update backend destination in demo

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars

Remove the Demo config for PIP as it is getting in the way for fix
```
[ ] Yes
[ x ] No
```

Add PIP Demo fix

---

environments/dev/dev.tfvars

- Add dev-00 load balancers ip to dev app gw
```
[ ] Yes
[x] No
```

Add 00 dev cluster to app gw

---

environments/dev/dev.tfvars

- added the wrong ip in my last pr
```
[ ] Yes
[x] No
```

Fix ip address

---

environments/stg/stg.tfvars

Add a link to an external cert imported in to Azure Key Vault for TLS domain validation
```
[ ] Yes
[x] No
```

Use an external certificate to validate https for the frontend domain

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-7085
Re-enable ssl for staging-casetracker
```
[ ] Yes
[x] No
```

Re-enable ssl to

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-7085
re-enable ssl
```
[ ] Yes
[x] No
```

Reset enable_ssl

---

environments/ithc/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

correct component name for pip frontend
```
[ ] Yes
[ x ] No
```

correct component name for pip frontend

---

azure-pipelines.yaml
environments/dev/dev.tfvars

add apim dev
```
[ ] Yes
[X] No
```

add apim dev

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-1178
New exclusion on pipfrontendstg
```
[ ] Yes
[X] No
```

PUB-1179 new-formcookie-exclusion

---

azure-pipelines.yaml
environments/stg/stg.tfvars
environments/test/test.tfvars

add apim stg
```
[ ] Yes
[X] No
```

add apim stg

---

environments/dev/dev.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

Refactor the dev and staging entries to match the amended DNS pattern of "dev." and "staging." Remove the old staging-casetracker front door entry which used an external cert
```
[ ] Yes
[x] No
```

Rst 4090 afd add dts legacy apps dev stg prod

---

environments/test/test.tfvars

Update FW dns name in  test.tfvars for pip

---

environments/stg/stg.tfvars

add sds-apim to stg frontdoor
```
[ ] Yes
[X] No
```

add sds-apim to stg frontdoor

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/RST-4367
Admin/Commissioners page is blocked by AFD managed rule
```
[ ] Yes
[x] No
```

Admin/Commissioners page is blocked by AFD managed rule

---

environments/ithc/backend_lb_config.yaml

PUB-1240
Remove PIP Frontend from ITHC Backend Config
```
[ ] Yes
[ x ] No
```

PUB-1240 - Remove PIP from ITHC backend

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/RST-4380
Session affinity was not the solution to the paging problem and actually break paging after the true website fix
```
[ ] Yes
[x] No
```

Session affinity breaks paging in website

---

environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars

PUB-1240
Add the PIP Frontend application to the ITHC Frontdoor
```
[ ] Yes
[ x ] No
```

PUB-1240 - Add PIP Frontend to the ITHC Frontdoor

---

environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars

PUB-1240
Correct the DNS values for PIP Frontdoor ITHC
```
[ ] Yes
[ x ] No
```

PUB-1240 - Correct ITHC Details for PIP Frontdoor

---

environments/demo/demo.tfvars

DTSPO-6491
Change IP address for demo private load balancer
```
[ ] Yes
[X] No
```

DTSPO-6491 - Change IP address for demo private load balancer

---

environments/demo/backend_lb_config.yaml

DTSPO-6491
Add toffee to backend load balancer config
```
[ ] Yes
[X] No
```

DTSPO-6491 - Add toffee to backend load balancer config

---

environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars

remove pip from demo and ithc
```
[ ] Yes
[ x ] No
```

remove pip from demo and ithc

---

azure-pipelines.yaml
components/apim/main.tf
environments/prod/prod.tfvars

add apim premium to prod
```
[ ] Yes
[X] No
```

add apim premium to prod

---

environments/prod/prod.tfvars

PUB-1061
Add configuration for Azure B2C
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-domain?pivots=b2c-custom-policy#custom-domain-overview
```
[ ] Yes
[ x ] No
```

PUB-1061 - add records for pip b2c

---

azure-pipelines.yaml
environments/test/test.tfvars

add apim to test env
```
[ ] Yes
[X] No
```

add apim to test env

---

environments/test/test.tfvars

change sds-apim-test backend domain
```
[ ] Yes
[X] No
```

change sds-apim-test backend domain

---

azure-pipelines.yaml
environments/demo/demo.tfvars
environments/ithc/ithc.tfvars

add apim demo and ithc
```
[ ] Yes
[X] No
```

add apim demo and ithc

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars

[PUB-1061](https://tools.hmcts.net/jira/browse/PUB-1061)
Remove PIP Sign-in URL
```
[ ] Yes
[ x ] No
```

Remove PIP Sign-in URL

---

environments/demo/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/DTSPO-8837
Remove toffee from demo backend config
```
[ ] Yes
[x] No
```

DTSPO-8837 - Remove toffee from demo backend

---

environments/stg/stg.tfvars

Comment out pip b2c staging config
```
[ ] Yes
[ x ] No
```

Comment out pip b2c staging config

---

README.md

Add information about shutter pages
```
[ ] Yes
[ x ] No
```

Add information about shutter pages

---

environments/prod/prod.tfvars

Change the PIP Frontdoor Names for the custom domains
```
[ ] Yes
[ x ] No
```

Correct PIP FD names

---

environments/prod/prod.tfvars

Remove PIP FD Config
```
[ ] Yes
[ x ] No
```

Remove PIP FD Config

---

environments/prod/prod.tfvars

Readd the PIP Configuration
```
[ ] Yes
[ x ] No
```

Readd the PIP Configuration

---

components/frontdoor/init.tf
components/frontdoor/main.tf

Reverts hmcts/sds-azure-platform#206
Fix issues raised in https://tools.hmcts.net/jira/browse/DTSPO-8980 and https://response.platform.hmcts.net/incident/70/

Revert "DTSPO-8837 - Azurerm v3 provider frontdoor"

---

environments/prod/prod.tfvars

Added change to allow the CookiePolicy cookie in prod
JIRA: https://tools.hmcts.net/jira/browse/PUB-1408
```
[ ] Yes
[x] No
```

Added cookiePolicy cookie to be allowed for prod P&I

---

environments/prod/prod.tfvars

N/A
Added query param exclusion for PIP
```
[ ] Yes
[x] No
```

Add exclusion for PIP

---

environments/prod/prod.tfvars

N/A
Updated exclusions
```
[ ] Yes
[x] No
```

Updated exclusions

---

components/apim/main.tf

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-8837
Change description
Use main branch for apim module
Depends on hmcts/cnp-module-api-mgmt-private#35 being merged first
No infrastructure changes to apim are taking place
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

DTSPO-8837 - Use main branch for apim module

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

N/A
Updated cookie policy name
```
[ ] Yes
[x] No
```

Updated cookie name for PIP

---

environments/stg/stg.tfvars

Updated PIP STG values to match PROD
```
[ ] Yes
[x] No
```

Updated PIP STG values to match PROD

---

environments/sbox/sbox.tfvars

Add shutter for vh service web SBOX
```
[ ] Yes
[ x ] No
```

Add shutter for vh service web SBOX

---

README.md

Add information on Frontdoor setup and TLS setup
```
[ ] Yes
[ x ] No
```

Update Readme with more information

---

environments/prod/prod.tfvars
environments/test/test.tfvars

PIP Add exclutions for B2C WAF
```
[ ] Yes
[ x ] No
```

PIP Add exclutions for B2C WAF

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

Update pre-commit.yml to match azure-platform-terraform
```
[ ] Yes
[X] No
```

Update pre-commit.yml to match azure-platform-terraform

---

environments/prod/prod.tfvars

N/A
Updated firewall
```
[ ] Yes
[x] No
```

Updated firewall

---

environments/dev/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/RST-4467
Configure new lgy-iac-web application in dev and stg env
```
[ ] Yes
[x] No
```

Add lgy-iac-web backend config for dev and stg environments

---

environments/test/test.tfvars

Updated PIP test cookie 
```
[ ] Yes
[x] No
```

Updated pip test cookie

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

VIH-9148
Add VH Wowza Frontdoor to public LB
```
[ ] Yes
[ x ] No
```

VIH-9148 - Add VH Wowza Frontdoor to public LB

---

environments/stg/stg.tfvars

VIH-9224
Update Staging URLs
```
[ ] Yes
[ x ] No
```

VIH-9224 - Update VH Staging URLs

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

VIH-9224
Remove WOWZA config
```
[ ] Yes
[ x ] No
```

VIH-9224 - Remove WOWZA config

---

environments/stg/stg.tfvars

VIH-9224
Comment out VH Staging Config before readding it
```
[ ] Yes
[ x ] No
```

VIH-9224 - Remove VH Staging Config

---

environments/stg/stg.tfvars

VIH-9224
Re-Add VH Staging Configuration
```
[ ] Yes
[ x ] No
```

VIH-9224 - Re-Add VH Staging Configuration

---

environments/stg/stg.tfvars

VIH-9224 
Rename VH Staging Config
```
[ ] Yes
[ x ] No
```

VIH-9224 - Rename VH Staging Config

---

environments/dev/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

Update DNS for Dev, ITHC, Test
```
[ ] Yes
[ ] No
```

VIH-9999 - Update DNS for Dev, ITHC, Test

---

environments/stg/backend_lb_config.yaml

Reverts hmcts/sds-azure-platform#261

Revert "Add c100 stg to VPN"

---

environments/stg/stg.tfvars

Add custom health path for c100
```
[ ] Yes
[x] No
```

C100 - custom health path

---

environments/prod/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/DTSPO-9055
Update toffee-backend to toffee-recipe-backend in prod backend lb
```
[ ] Yes
[x] No
```

DTSPO-9055 - Update toffee backend lb config prod

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-9055
Fix error related to pip-frontend on ithc frontdoor
```
[ ] Yes
[x] No
```

DTSPO-9055 - Fix pip-frontend ithc

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-9055
Re-add ithc frontdoor endpoints
```
[ ] Yes
[x] No
```

DTSPO-9055 - Fix ithc frontdoor - part 2

---

azure-pipelines-frontdoor.yaml

https://tools.hmcts.net/jira/browse/DSTPO-9055
Update test_title
```
[ ] Yes
[x] No
```

Fix frontdoor test titles

---

environments/test/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/DTSPO-9981
Added Libra Gob Integration Services product to test backend config.
```
[ ] Yes
[ x ] No
```

feat: added test libra gob product

---

environments/test/backend_lb_config.yaml

*
Updated Libra GoB host_name_prefix.
```
[ ] Yes
[X] No
```

Updated Libra GoB host_name_prefix.

---

environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

VIH-9377
add WAF exclusions for VH.
```
[ ] Yes
[ x ] No
```

VIH-9377 - Add WAF exclusions

---

environments/stg/stg.tfvars

Amend staging front door config for VH Apps.
```
[ ] Yes
[ x ] No
```

VIH-9999 - Amend staging front door config

---

environments/stg/stg.tfvars

comment out VH due to issues with pipeline
```
[ ] Yes
[ x ] No
```

VIH-9999 - comment out VH due to issues with pipeline

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-942
Updated firewall to allow iss to come through when signing in via CFT IDAM
```
[ ] Yes
[x] No
```

PUB-942 - Updated firewall

---

environments/dev/dev.tfvars

VIH-9999 - Disable Cache in Dev AFD
VIH-9999 - Disable Cache in Dev AFD
```
[ ] Yes
[x ] No
```

VIH-9999 - Disable Cache in Dev AFD

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/PUB-1600
Allowed error_description that can be sent during the sign in process
```
[ ] Yes
[x] No
```

PUB-1600 - Updated prod tfvars for pip

---

environments/dev/dev.tfvars

VIH-9409
- Add PR release public for testing cache
```
[ ] Yes
[ x ] No
```

VIH-9409 - Add PR release public for testing cache

---

environments/dev/backend_lb_config.yaml
environments/dev/dev.tfvars

VIH-9409
VIH-9409 - Add AppGw Config for Front Door PR 
```
[ ] Yes
[x ] No
```

VIH-9409 - Add AppGw Config

---

environments/stg/stg.tfvars

Update stg.tfvars
```
[ ] Yes
[x ] No
```

VIH-9999 - Update stg.tfvars

---

environments/sbox/sbox.tfvars

remove caching from pre recorded sbox
```
[ ] Yes
[X] No
```

remove caching from pre recorded sbox

---

environments/sbox/sbox.tfvars

removing caching from front door for pre-rec-evidence sbox because seeing redirect errors when connecting
```
[ ] Yes
[ x] No
```

Adding WAF rule GB access to front door

---

environments/demo/demo.tfvars
environments/test/test.tfvars

Adding demo and test environments to use front door for pre-recorded-evidence. Sbox already implemented and working.
```
[ ] Yes
[ x] No
```

Adding demo and test to front door for pre-recorded-evidence

---

environments/prod/prod.tfvars

VIH-9445
Amend Production DNS for VH
```
[ ] Yes
[x ] No
```

VIH-9445 - Amend Production DNS for VH

---

environments/prod/prod.tfvars

VIH-9445 - Remove Test Web & Service Web
VIH-9445 - Remove Test Web & Service Web
```
[ ] Yes
[ x ] No
```

VIH-9445 - Remove Test Web & Service Web

---

environments/dev/backend_lb_config.yaml
environments/dev/dev.tfvars

VIH-9478 - Amend Traffic Flow
VIH-9478 - Amend Traffic Flow
```
[ ] Yes
[x ] No
```

VIH-9478 - Amend Traffic Flow

---

environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/backend_lb_config.yaml
environments/test/test.tfvars

VIH-9478 - Amend AppGws
```
[ ] Yes
[x ] No
```

VIH-9478 - Amend AppGws

---

environments/prod/prod.tfvars

VIH-9999 - Rollback VH URLs
```
[ ] Yes
[ x ] No
```

VIH-9999 - Rollback VH URLs

---

azure-pipelines-frontdoor.yaml
azure-pipelines.yaml

swapping kv from infra-vault-sbox to infra-vault-nonprod
```
[ ] Yes
[X] No
```

swapping kv from infra-vault-sbox to infra-vault-nonprod

---

environments/dev/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/sbox/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

N/A
Removing vh-scheduler-jobs and vh-booking-queue-subscriber from all VH app gateway back end environments
```
[ ] Yes
[ X] No
```

VIH-9999 Remove scheduler and booking queue from all envs

---

components/frontdoor/main.tf

Reverting landing zone module back to the master branch 
```
[ ] Yes
[x] No
```

Revert landing zone module to master branch

---

components/appgateway/main.tf
components/backendappgateway/main.tf

https://tools.hmcts.net/jira/browse/DTSPO-10836
Update module branches
```
[ ] Yes
[x] No
```

DTSPO-10836 - update module branches

---

components/frontdoor/main.tf

DTSPO-11787.   Sbox ADD new tag

---

components/apim/main.tf
components/appgateway/main.tf
components/backendappgateway/main.tf
components/shutter/module_shutter.tf
components/trafficmanager/main.tf
environments/variable.tf

Set expiresAfter tag to 3000-01-01 so sandbox resources do not get deleted
```
[ ] Yes
[x] No
```

DTSPO-11790 - add expiresAfter tag

---

environments/dev/dev.tfvars

VIH-9446 - Add PR release for testing
VIH-9446 - Add PR release for testing
```
[ ] Yes
[x ] No
```

VIH-9446 - Add PR release for testing

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-1809
Add WAF exclusions for PIP_frontend:
- Cookie 'session.sig'
- Dynatrace cookie 'dtSa'
```
[ ] Yes
[x] No
```

PUB-1809 Add WAF exclusions for PIP-frontend

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-1897
Attempt 1 at fixing the Manual Upload path traversal false positive.
Only deploying to test env.
```
[ ] Yes
[x] No
```

PUB-1897 - Updated test tf vars

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-12425
Adds SDS applications to Front door and App gw
```
[ ] Yes
[ ] No
```

Add remaining FE & BE apps to FD and APPGW

---

environments/sbox/sbox.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/S28-1030
Disabling WAF rules in sbox and test as causing 403 errors when using portal. Will deploy to demo/stg/prod at later date once these changes are confirmed as good.
```
[ ] Yes
[ x] No
```

Adding WAF exclusions to fix issues using the PRE portal

---

renovate.json

Enable auto-merge for renovate PRs
```
[ ] Yes
[x] No
```

DTSPO-11734 - enable automerge

---

renovate.json

Set renovate schedule to `after 7am and before 11am every weekday`
```
[ ] Yes
[x] No
```

DTSPO-11734 - renovate - set schedule

---

environments/dev/dev.tfvars

Add config for pre-dev
```
[ ] Yes
[x] No
```

Add PRE dev

---

environments/demo/backend_lb_config.yaml
environments/dev/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/sbox/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/DMP-42
adding the config for the darts api and gateway load balancer 
```
[ ] Yes
[x] No
```

darts modernisation api and gateway added to load balancer config

---

environments/ithc/ithc.tfvars

testing with ithc environment

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/prod/prod.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-13210
Updating remaining  prod, demo, dev and test environments to tls 1.2
```
[ ] Yes
[ X ] No
```

upgrading rest of the environment to tls1.2

---

environments/sbox/sbox.tfvars

Adding DARTS portal sandbox env config

---

environments/prod/prod.tfvars

VIH-0000 - Amend Prod URLS for VH Cutover
```
[ ] Yes
[ x ] No
```

VIH-0000 - Amend Prod URLS for VH Cutover

---

environments/prod/prod.tfvars

VIH-0000 - Rollback Video Hearings
```
[ ] Yes
[ x ] No
```

VIH-0000 - Rollback Video Hearings

---

components/frontdoor/init.tf
components/frontdoor/main.tf

see https://github.com/hmcts/terraform-module-frontdoor/pull/32

Remove unused subscription variable

---

environments/stg/stg.tfvars

INC5506713
Added exclusion for false positive on post variable for CaTH into Staging
```
[ ] Yes
[x] No
```

Added subscriptions exclusion to staging

---

environments/prod/prod.tfvars

INC5506713
Fix false positive on subscriptions post request in prod for cath
```
[ ] Yes
[x] No
```

Add subscriptions exclusion for CaTH

---

components/apim_appgw/main.tf

update the identity name

---

environments/prod/prod.tfvars

VIH-0000 - Amend Prod URLS for VH Cutover
```
[ ] Yes
[X] No
```

VIH-0000 - Amend Prod URLS for VH Cutover 

---

environments/prod/prod.tfvars

Add ejudiciary.net redirect

---

azure-pipelines.yaml
components/apim_appgw/init.tf
components/apim_appgw/local.tf
components/apim_appgw/main.tf
components/backendappgateway/main.tf
environments/demo/apim_appgw_config.yaml
environments/demo/demo.tfvars
environments/dev/apim_appgw_config.yaml
environments/dev/dev.tfvars
environments/ithc/apim_appgw_config.yaml
environments/ithc/ithc.tfvars
environments/sbox/apim_appgw_config.yaml
environments/sbox/sbox.tfvars
environments/test/apim_appgw_config.yaml
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-13623
Added application gateway with mtls (Client Authentication) to all the demo, dev, ithc, sbox and test environemtns.
```
[ ] Yes
[ X ] No
```

testing ssl profiles

---

components/apim_appgw/main.tf
environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/test/test.tfvars
environments/variable.tf

updated autoscaling instances for non prod environments.
```
[ ] Yes
[X ] No
```

changed nonprod environaments instances

---

azure-pipelines.yaml
components/apim/main.tf

**Change**
Commented Prod and STG environments as the module change here contains breaking change..
https://github.com/hmcts/cnp-module-api-mgmt-private/pull/37

updated module to test gateways

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

The app manages a cache internally so does not require FD caching as this is causing issues during deployments
```
[ ] Yes
[X] No
```

VIH-0000 Disable AFD cache for VH

---

environments/sbox/sbox.tfvars

Disable shutter

---

components/apim_appgw/main.tf
environments/demo/apim_appgw_config.yaml

https://tools.hmcts.net/jira/browse/DTSPO-13624 
Added rewrite rule to test on Demo environment
```
[ ] Yes
[ X ] No
```

added rewrite rule branch

---

environments/test/test.tfvars

[VIH-9912](https://tools.hmcts.net/jira/browse/VIH-9912)
Add VH test exclustions
```
[ ] Yes
[X] No
```

VIH-9912 Add VH test exclustions

---

environments/test/test.tfvars

N/A
Add missing exclusion from the PIP test environment for form cookie (which is used during manual upload)
```
[ ] Yes
[x] No
```

PIP Update Config for Test Env

---

environments/demo/demo.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

N/A
- for OpenID callbacks etc
```
[ ] Yes
[x] No
```

Adding global_exclusions for DARTS frontdoor configuration

---

environments/dev/backend_lb_config.yaml

* Dev: Update backend Appgw IP to 10.145.32.135
```
[ ] Yes
[x] No
```

Dev: Update backend Appgw IP to 10.145.32.135

---

environments/prod/prod.tfvars

Adding darts-portal prod entry

---

components/apim/init.tf
components/apim_appgw/init.tf
components/appgateway/init.tf
components/backendappgateway/init.tf
components/frontdoor/init.tf
components/trafficmanager/init.tf

Reverts hmcts/sds-azure-platform#419

Revert "chore(deps): update terraform azurerm to v3.61.0"

---

environments/demo/demo.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

N/A
Adding prod config for DARTS portal and disabling cache for all envs
```
[ ] Yes
[X] No
```

DARTS portal: Add prod and disable cache

---

environments/demo/demo.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

Reverts hmcts/sds-azure-platform#470

Revert "DARTS portal: Add prod and disable cache"

---

azure-pipelines.yaml
components/shutter_static_webapp/init.tf
components/shutter_static_webapp/resource_group.tf
components/shutter_static_webapp/static_webapp.tf
components/shutter_static_webapp/variables.tf
environments/sbox/sbox.tfvars

Dtspo- 14285 Create new shutter infra

---

components/shutter_static_webapp/data.tf
components/shutter_static_webapp/init.tf
components/shutter_static_webapp/static_webapp.tf

Update shutter webapp config

---

components/shutter_static_webapp/static_webapp.tf

dtspo-14285 pass env variable to static webapp module

---

environments/prod/backend_lb_config.yaml

*
Add Libra GoB Integration Service backend config
```
[ ] Yes
[X] No
```

Add Libra GoB Integration Service backend config

---

components/apim/local.tf
components/apim_appgw/local.tf

https://tools.hmcts.net/jira/browse/DTSPO-14613
DTSPO-14613: Cleanup UKWEST refs in repo
```
[ ] Yes
[x] No
```

DTSPO-14613: Cleanup UKWEST refs in repo

---

azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-14613
Changed the pipeline tests = true to false in relation to apim.
```
[ ] Yes
[x] No
```

DTSPO-14613: Pipeline Tests

---

environments/prod/prod.tfvars

unshutter toffee

---

components/shutter/module_shutter.tf

DO NOT MERGE:  Remove old shutter solution

---

environments/dev/dev.tfvars

https://tools.hmcts.net/jira/browse/VIH-10085
Whitelist video web PR url for Kinly/Pexip
```
[ ] Yes
[x] No
```

VIH-10085 Update dev to whitelist pr url

---

environments/demo/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/PUB-1763
Setting up demo env for PIP. Enabling https on backends.
```
[ ] Yes
[x] No
```

PUB-1763 - Enabling https on the demo backend

---

environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/PUB-1763
Updated demo firewall to be the same as prod
```
[ ] Yes
[x] No
```

PUB-1763 - Updated demo firewall to be the same as prod for pip

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/PUB-1897
Fix false positive with Manual Upload in CaTH
```
[ ] Yes
[x] No
```

PUB-1897 - False Positive CaTH

---

components/appgateway/main.tf
components/backendappgateway/main.tf
environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars
environments/variable.tf

Add autoshutdown tag to app gateways

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars
environments/dev/backend_lb_config.yaml
environments/dev/dev.tfvars
environments/prod/backend_lb_config.yaml
environments/prod/prod.tfvars
environments/sbox/backend_lb_config.yaml
environments/sbox/sbox.tfvars
environments/stg/backend_lb_config.yaml
environments/stg/stg.tfvars
environments/test/backend_lb_config.yaml
environments/test/test.tfvars

PRE is moving to AKS so we need to use the platform.hmcts.net domain to make use of features like [deployment previews](https://hmcts.github.io/cloud-native-platform/guides/pr-url.html) linked on prs.
```
[ ] Yes
[x] No
```

Add PRE to FD and APPGW

---

environments/sbox/sbox.tfvars

correct pre-portal to point to sandbox not sbox

---

components/frontdoor/main.tf

DTSPO-13992 updating provider to fix pipeline

---

environments/demo/demo.tfvars
environments/test/test.tfvars

N/A
Ensure lower environments are in sync on pip
```
[ ] Yes
[x] No
```

Ensure lower environments are in sync for pip

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-2115
Add exclusion to test environment for pip for new session cookie
```
[ ] Yes
[x] No
```

PUB-2115 - Updated exclusion for new cookie

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

N/A
Disable caching for DARTS portal

Disabling frontdoor caching for DARTS portal

---

environments/demo/demo.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/PUB-2115
Added exclusion for session cookie
```
[ ] Yes
[x] No
```

PUB-2115 - Added exclusion for pip

---

components/frontdoor/diagnostics.tf

Will be used instead of log analytics for high traffic logs we don't access very much

Add diagnostics storage account

---

components/appgateway/diagnostics.tf
components/appgateway/main.tf
components/backendappgateway/diagnostics.tf
components/backendappgateway/main.tf

Follow on to https://github.com/hmcts/sds-azure-platform/pull/576

Send App gateway logs to storage account

---

azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-13993
turning off sbox frontdoor stage for migration

turning off sbox frontdoor for migration

---

azure-pipelines.yaml
components/frontdoor/init.tf
components/frontdoor/main.tf
environments/sbox/sbox.tfvars
environments/variable.tf

https://tools.hmcts.net/jira/browse/DTSPO-13993
Migrated sbox frontdoor to premium
- [ X ] commit messages are meaningful and follow good commit message guidelines

DTSPO-13993 - migrated sbox frontdoor

---

environments/demo/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml

n/a
Add Juror Scheduler-API to demo and staging backend app gateway
- [] README and other documentation has been updated / added (if needed)
- [] tests have been updated / new tests has been added (if needed)
- [] Does this PR introduce a breaking change

Add Juror Scheduler-API to demo and staging

---

environments/dev/dev.tfvars

remove certificate_name field so we use microsoft managed certs instead of ACME

Update pre-portal dev.tfvars

---

environments/demo/demo.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-2117
Added redirects for staff/sign-in links to B2C on demo and test for PIP.

Added redirects for staff/sign-in links to B2C on demo and test

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-15319
* add netbox sandbox FD config for app proxy redirect

Sandbox: add netbox sandbox FD config for app proxy redirect

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-15319
* Add Netbox PTL Prod FD Redirect

Add Netbox PTL Prod FD Redirect to App Proxy URL

---

azure-pipelines.yaml
environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-15149
Disable production frontdoor stage to prepare for migration

DTSPO-15149 - Turn off SDS Prod pipeline stage

---

components/frontdoor/main.tf

https://tools.hmcts.net/jira/browse/DTSPO-13992
Updated Frontdoor branch

DTSPO-13992 - updated frontdoor branch

---

environments/demo/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml

add_juror_pnc

---

environments/stg/backend_lb_config.yaml

Add Opal backend

---

environments/demo/demo.tfvars
environments/stg/stg.tfvars

add juror public

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars

DMP-1646-Darts-portal-url

---

environments/stg/stg.tfvars

Add Opal frontend to staging

---

components/frontdoor/main.tf
environments/variable.tf

- Tested the module
- removed unneeded variable

Tested heritage changes module and removed unneeded variable

---

components/frontdoor/main.tf

https://tools.hmcts.net/jira/browse/DTSPO-14559
Revert front door module to master branch from cdn-versionless
Change from module branch has been merged

DTSPO-14559 - Revert front door to master branch

---

environments/demo/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml

https://centralgovernmentcgi.atlassian.net/browse/JM-5597

Juror: add jse

---

azure-pipelines.yaml

Dtspo 15333 auto start env in ado

---

environments/demo/demo.tfvars
environments/stg/stg.tfvars

https://centralgovernmentcgi.atlassian.net/browse/JM-5521 
Alter urls șo far (just juror-public) to use .apps.hmcts.net
- [] Does this PR introduce a breaking change

move juror-public to apps.hmcts.net

---

environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars
environments/test/backend_lb_config.yaml
environments/test/test.tfvars

Add backend LB and frontend for Juror services in test and itch

add juror to test and ithc

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

juror: add bureau

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

Take whitelist from existing bureau app and re-use for juror-bureau

whitelists on bureau for test, ithc, demo and staging

---

environments/stg/stg.tfvars

Add SQLI rule to disabled_rules in stg.tfvars

---

environments/demo/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

add juror api

---

environments/stg/backend_lb_config.yaml

Add Opal Legacy Stub

---

environments/stg/backend_lb_config.yaml

[PO-193](https://tools.hmcts.net/jira/browse/PO-193)
Add Opal Print Service

Add Opal Print Service

---

environments/demo/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

juror need to override the health endpoint for the time being to /health to deal with our custom health endpoint. 
a ticket is in the backlog for removing of said custom health endpoint.

juror: api health path override

---

environments/stg/backend_lb_config.yaml

PO-214: Add Opal log and audit service

---

environments/stg/stg.tfvars

juror: stg frontdoor testing

---

environments/demo/backend_lb_config.yaml

add affinity cookie name

---

environments/stg/stg.tfvars

juror: staging update

---

environments/demo/backend_lb_config.yaml

escape curly braces

---

environments/stg/stg.tfvars

juror: add 942260

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars

Add known disabled rules to WAFs and set ITHC in Detection mode

amend WAF for Juror ITHC and Prod

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/PUB-2298
Updated PIP ITHC Frontend to be in-sync with the other environments

PUB-2298 - Updated PIP ITHC to be in sync

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

update juror rules

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/PUB-2298
Added B2C paths for ITHC pip

PUB-2298 - Updated ITHC config for pip

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

juror: add waf rules to test

---

environments/demo/demo.tfvars

remove this line so we're able to toggle shuttering

Update pre demo shutter setting

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

juror: fix pipeline

---

environments/demo/demo.tfvars

I'm testing. domain not currently in use.

Update PRE demo.tfvars

---

environments/prod/prod.tfvars

Update cache-enabled to false for cicap

---

environments/demo/demo.tfvars

juror: switch demo to detection mode with waf rules

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DMP-2534
For staging only, to test before setting on other environments.

DMP-2534 Update DARTS portal cookie exclusions

---

environments/test/backend_lb_config.yaml

N/A
Increase LibraGoB timeout in test to match prod.

feat: bump timeout for LibraGoB test to match prod

---

environments/ithc/ithc.tfvars

update ithc to be in prevention mode

update ithc to be in prevention mode

---

environments/prod/prod.tfvars

attempt2 fmt

---

components/apim/main.tf
environments/ithc/ithc.tfvars
environments/variable.tf

changed vars to object for better readability and validation on module side
Request to AEP failed to process

DTSPO-17136-apim-upgrade-improvements

---

environments/stg/stg.tfvars

N/A
- Added a new match_variable and its configuration related to \"QueryStringArgNames\" for the frontends configuration.
- The new match_variable configuration includes the operator \"Equals\" and the selector \"user_ids\".

Adding query string exclusion for DARTS portal

---

environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/sbox/sbox.tfvars
environments/test/test.tfvars

N/A
- except prod, which is not set up yet
Request to AEP failed to process

Ensure DARTS portal WAF exclusions are on all envs

---

environments/dev/dev.tfvars

migrating sds dev apim stv2
- Updated `dev.tfvars`:
- Added migration variables for triggering migration and specifying subnet address prefixes.

add migration variable in dev tfvars

---

environments/dev/dev.tfvars

trigger migration false for dev
- `dev.tfvars`:
- Changed `trigger_migration` from `true` to `false`.

DTSPO-17763-apim-upgrade-dev-migrate-back

---

environments/dev/dev.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17763
Resource clean up for sds api mgmt dev
- Updated dev.tfvars
- Changed the value of trigger_migration_temp_pip from true to false in the migration_variables.

DTSPO-17763-sds-apim-dev-resource-cleanup

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17759
added migration vars and start migration
- ithc.tfvars```
- Added migration variables for triggering migration and specifying subnet address prefixes.
- Updated SSL policy configuration.
- Updated key vault subscription and private IP addresses for application gateway.

added migration vars for ithc, ready to migrate

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars

sds demo upgrade - https://tools.hmcts.net/jira/browse/DTSPO-17760
sds ithc code clean up - https://tools.hmcts.net/jira/browse/DTSPO-17759
added migration vars for sds apim demo
temp resource clean up for sds apim ithc
- File: demo.tfvars
- Added migration variable with trigger_migration set to true, trigger_migration_temp_pip set to true, and temp_subnet_address_prefixes set to \"10.51.99.0/24\".
- Updated ssl_policy with min_protocol_version set to \"TLSv1_2\".
- File: ithc.tfvars
- Updated migration_variables with trigger_migration_temp_pip set to false.
- Updated temp_subnet_address_prefixes to \"10.143.35.0/24\".

code cleanup sds apim ithc and added migration vars for sds apim demo

---

environments/demo/demo.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17762
added migration vars for sds apim test
code cleanup for sds apim demo
- `demo.tfvars`:
- Changed `trigger_migration_temp_pip` from true to false in `migration_variables`.
- `test.tfvars`:
- Added `migration_variables` with `trigger_migration` set to true, `trigger_migration_temp_pip` set to true, and `temp_subnet_address_prefixes` set to \"10.141.35.0/24\".

upgrade sds apim test and cleanup sds apim demo

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17762
removed migration vars for sds apim test no longer needed, code cleanup 
- Removed migration_variables block containing trigger_migration, trigger_migration_temp_pip, and temp_subnet_address_prefixes.
- Updated key_vault_subscription to \"3eec5bde-7feb-4566-bfb6-805df6e10b90\".
- Updated apim_appgw_backend_pool_fqdns to include \"firewall-nonprodi-palo-sdsapimgmttest.uksouth.cloudapp.azure.com\".

code cleanup sds apim test

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17761
set migration vars to false, trigger upgrade pt 2 for sds apim 
- **environments/stg/stg.tfvars**
- Changed `trigger_migration` from `true` to `false` and `trigger_migration_temp_pip` to `true`.
- Updated `temp_subnet_address_prefixes` to \"10.148.35.0/24\".

sds apim stg for upgrade pt2

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17761
trigger migration temp to false
- In the `environments/stg/stg.tfvars` file, the value of `trigger_migration_temp_pip` has been changed from `true` to `false`.

cleanup apim sds stg temp resources

---

components/apim/main.tf
environments/variable.tf

removed migration vars
- Removed the `migration_variables` from the `module \"api-mgmt\"` block.
- Removed the `migration_variables` block containing migration-related variables.

revert apim module, apim upgrade complete

---

environments/prod/prod.tfvars
environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17037
Removing netbox
- Changed `prod.tfvars`:
- Removed configuration for the \"netbox\" product.
- Changed `sbox.tfvars`:
- Removed configuration for the \"netbox\" product.

DTSPO-17037 - removed netbox

---

azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17593
Dynamically set pipeline name
Request to AEP failed to process

DTSPO-17593 - dynamic pipeline name

---

azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17593
Updated so it will allow dynamic name for manual pipeline  run
Request to AEP failed to process

DTSPO-17593 - allow dynamic pipeline name

---

environments/prod/prod.tfvars

add Liam to AFD rules for go-live testing
- `prod.tfvars`:
- Added the IP address `90.248.134.4` to the list of frontends. 🌐

add Liam to AFD rules for go-live testing

---

environments/prod/prod.tfvars

- Added the IP address \"217.44.63.146\" to the list of frontends. 🛠️

Add ben to whitelist for go-live testing

---

environments/stg/backend_lb_config.yaml

https://centralgovernmentcgi.atlassian.net/browse/PDDA-393
added lb config for pdm
- [ X] commit messages are meaningful and follow good commit message guidelines
- [No ] Does this PR introduce a breaking change
- **backend_lb_config.yaml**
- Added a new configuration for `public-display-manager` with SSL enabled.

added lb config for pdm

---

environments/stg/backend_lb_config.yaml

Add opal-service-auth-provider and opal-external-api
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
- [ X] Does this PR introduce a breaking change
- **backend_lb_config.yaml**
- Added SSL configuration for `service-auth-provider` and `external-api` components of `opal`.

Declan clarke cgi patch 1

---

.github/workflows/pre-commit.yml
environments/prod/prod.tfvars

Testing out a solution by adding a venv into the precommit as it's currently failing on the operating system/environment has restricted direct package installations through pip
- Added steps to create and activate a virtual environment
- Installed pre-commit within the virtual environment
- Updated setup-python action from v4 to v4.43.1
- Updated pre-commit/action from v3.0.1 to v3.0.1

Adding python venv to fix issue on the precommit

---

azure-pipelines.yaml
environments/test/test.tfvars

- Removed the \"cluster\" and \"environment\" fields from the pipeline configuration.
- Updated the \"mode\" field from \"Prevention\" to \"Detection\" for the \"pre-portal\" frontend.

PRE- detect for testing Update test.tfvars

---

environments/test/test.tfvars

- The `test.tfvars` file in the `test` environment has changes related to the frontend configurations. 
- Specifically, it includes the addition of a new frontend configuration for \"pre-portal\" with mode \"Detection\".

comment out pre-justice URL in test.tfvars

---

environments/dev/dev.tfvars

N/A
- Updated `custom_domain` from \"darts.dev.apps.hmcts.net\" to \"darts.dev.platform.hmcts.net\"
- Updated `dns_zone_name` from \"apps.hmcts.net\" to \"dev.platform.hmcts.net\"

Fixing DARTS portal WAF exclusions on dev env

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/PUB-2663
Added exclusion rule for query param for SSO
- Added a new frontend configuration to match on `QueryStringArgNames` with operator \"Equals\" and selector \"code\".

PUB-2663 - Added exclusion

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-23473
Deploying to staging and PRP environment to run the shuttering tests.
- Added new configurations for tools-atlassian-prp and tools-atlassian-staging with shutter_app, custom_domain, and dns_zone_name properties.

DTSPO-23473 - Deploying shutter app for atlassian staging and prp

---

environments/ithc/ithc.tfvars

Test firewall ruleset upgrade in ITHC
- Added \"ruleset_type\" with value \"Microsoft_DefaultRuleSet\"
- Added \"ruleset_value\" with value \"2.1\"
- Cleared \"disabled_rules\" array

PUB-2727 Test firewall ruleset upgrade in ITHC

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-22779
Running Shutter page tests
- Added a new entry to the `additional_shutter_apps` array with the name \"test-shutter-app\" and specific domain information.

Testing Shutter app to see if we can deploy default page direclty

---

components/frontdoor/main.tf
environments/ithc/ithc.tfvars

Update disabled rule action for pip-frontend on ITHC
- Added a new key `disabled_rules_action` set to \"AnomalyScoring\" to the `frontends` configuration.
- Added a new rule to the `disabled_rules` for `General` category with rule ID \"200002\".

Do_not_merge PUB-2727 Update disabled rule action for pip-frontend on ITHC

---

environments/sbox/sbox.tfvars

Going to destroy post Show and tell
- Added a new entry for additional_shutter_apps including the name, shutter_app, dns_zone_name, and custom_domain for a test-shutter-app-new.

adding test static app

---

environments/prod/prod.tfvars

Remove redundant disabled rules setting in prod overriding the setting
md
- environments/prod/prod.tfvars
- Removed a block of disabled_rules and adjusted the formatting in the file.
```

PUB-2727 Remove redundant disabled rules setting in prod

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/PUB-2734
Updated firewall in ITHC for testing
- ithc.tfvars
- Removed global exclusions for frontends and pip-frontend-b2c-staff
- Added ruleset_type and ruleset_value for frontends and pip-frontend-b2c-staff

PUB-2778 - Updated firewall in ITHC for CaTH

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-2778
Update WAF to ruleset 2.1 for PIP B2C on test env
- `environments/test/test.tfvars`
- Updated the `ruleset_type` and `ruleset_value` for the frontends.
- Updated global_exclusions for both frontends.

PUB-2778 Update WAF to ruleset 2.1 for PIP B2C on test env

---

components/frontdoor/main.tf
environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-23861
enforce HTTPS via HSTS header for the `toffee` frontend in sbox
ADO ci pipeline
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=810112&view=results
- Updated sbox.tfvars:
- Changed the configuration for the \"toffee\" app frontend to include the addition of the \"hsts_header_enabled\" attribute set to \"true\".

to test a new frontdoor rule set 'hsts_rules'

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars

**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
- `backend_lb_config.yaml`:
- Added SSL configurations for opal, fines-service, legacy-db-stub, user-service, and file-handler components.
- `demo.tfvars`:
- Added opal-frontend configuration with custom domain, DNS zone, backend domain, and disabled security rules for SQL injection.

Add opal-frontend configuration to demo environment

---

environments/dev/dev.tfvars

[DTSPO-26128](https://tools.hmcts.net/jira/browse/DTSPO-26128)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
- Added a new \"priority\" field with a value of 2 to the traffic_manager_profiles for fw-uksouth-nonprodi-palo-mailrelay0-pip.
- Added a new \"priority\" field with a value of 1 to the traffic_manager_profiles for fw-uksouth-nonprodi-palo-mailrelay1-pip.

DSTPO-26128 sds azure daily pipeline check fix

---

environments/ithc/ithc.tfvars

updated Courtfines ITHC zone
- File: environments/ithc/ithc.tfvars
- Changed custom_domain from \"courtfines-app.ithc.apps.hmcts.net\" to \"courtfines-app.ithc.platform.hmcts.net\"
- Changed dns_zone_name from \"apps.hmcts.net\" to \"ithc.platform.hmcts.net\"

updated Courtfines ITHC zone

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/PUB-3010
Add rule exclusions for PIP caution message and no list message in test environment
This will be tested in test environment first to make sure the request is not blocked with the changes. Hence this PR.
- Modified test.tfvars in environments/test directory
- Added new match_variable, operator, and selector configurations for RequestBodyPostArgNames
- Added configurations for \"english-caution-message\", \"welsh-caution-message\", \"english-no-list-message\", and \"welsh-no-list-message\" within the frontends list

PUB-3010 Add rule exclusions for PIP in test environment
